### ISSUE TITLE
Headers is not defined error

### ISSUE THREAD

**Issue by sadiq1971** [definedfi/sdk#15]
Error:
```
/home/sadiq/chainsafe/uplink/uplink-indexer/uplink-indexer/node_modules/@definedfi/sdk/dist/sdk/index.js:23
            headers: new Headers({
                         ^

ReferenceError: Headers is not defined
    at new Defined (/home/sadiq/chainsafe/uplink/uplink-indexer/uplink-indexer/node_modules/@definedfi/sdk/dist/sdk/index.js:23:26)
    at updatePricing (/home/sadiq/chainsafe/uplink/uplink-indexer/uplink-indexer/lib/jobs/pricing.js:17:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

Code:

```
import { Defined } from '@definedfi/sdk'
const sdk  = new Defined(process.env.DEFINED_API_KEY || "")
```
dependency installed:
`"@definedfi/sdk": "^0.3.0"`

**Comment by bradens** [comment]
It's because we use the `Headers` class which is compatible with the web's Fetch implementation. 

https://nodejs.org/api/globals.html#class-headers

We should specify the node version required, which is now set here #21 

Solution is to upgrade to node 17.5.0
